### ISSUE TITLE
Consider alternative solution for sum-in-pairs (first challenge)

### ISSUE THREAD

**Issue by kkirsche** [subsr97/daily-coding-problem#2]
The first challenge has a simpler way of writing out a solution, in my opinion, which you may want to consider adding:

```python
from itertools import combinations

def determine_sum(numbers, neededSum):
    resulting_values = list(map(sum combinations(numbers, 2)))
    if neededSum in resulting_values:
        return True
    return False
```

This though I think is technically two passes rather than one, which may make it less ideal for the challenge

**Comment by subsr97** [comment]
Hi @kkirsche 

Your proposed solution uses inbuilt itertools.combinations which I believe wouldn't be allowed when your interview question is directly related to generating combinations.

There's more complexity involved here. You generate all possible combinations (which would take two passes) and then traverse once again to check if the neededSum is in the resulting_values (which would take one pass). So three passes in my opinion. 

Also it's almost similar to the brute force method in my solution. We find all possible combinations using two loops and return as soon as (if) we find a sum pair.
